import { NextRequest, NextResponse } from "next/server";
import { requireSession } from "@/lib/session";
import { prisma } from "@/lib/db";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const user = await requireSession();
  const orgId = user.memberships[0]?.orgId;

  const productLine = await prisma.productLine.findFirst({ where: { id, orgId } });
  if (!productLine) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { baseUrl: rawBaseUrl, email, apiToken: providedToken } = await request.json();
  const baseUrl = rawBaseUrl?.trim().replace(/\/+$/, "");

  if (!baseUrl || !email) {
    return NextResponse.json({ error: "baseUrl and email are required" }, { status: 400 });
  }

  // Use provided token or fall back to stored token
  let apiToken = providedToken;
  if (!apiToken) {
    const config = await prisma.jiraConfig.findUnique({ where: { productLineId: id } });
    if (!config) return NextResponse.json({ error: "No API token provided and no stored token found" }, { status: 400 });
    apiToken = config.apiToken;
  }

  try {
    const auth = Buffer.from(`${email}:${apiToken}`).toString("base64");
    const url = `${baseUrl}/rest/api/3/myself`;
    const res = await fetch(url, {
      headers: { Authorization: `Basic ${auth}`, Accept: "application/json" },
    });

    if (res.ok) {
      const data = (await res.json()) as { displayName?: string; emailAddress?: string };
      return NextResponse.json({ ok: true, displayName: data.displayName, emailAddress: data.emailAddress });
    } else {
      const body = await res.text();
      let rawMessage = `HTTP ${res.status}`;
      try {
        const parsed = JSON.parse(body) as { message?: string; errorMessages?: string[] };
        rawMessage = parsed.message ?? parsed.errorMessages?.[0] ?? rawMessage;
      } catch {}

      let error: string;
      let hint: string | undefined;

      if (res.status === 401) {
        error = "Authentication failed (401) — the email or API token is incorrect, or the token has expired.";
        hint = "Go to id.atlassian.com/manage-profile/security/api-tokens, create a new token, paste it in the API Token field above, and try again.";
      } else if (res.status === 403) {
        error = "Access denied (403) — the token doesn't have permission to access this Jira instance.";
        hint = "Make sure you're using a token generated by a user with access to this Jira workspace.";
      } else if (res.status === 404) {
        error = "Jira URL not found (404) — the base URL may be incorrect.";
        hint = "Check the Jira base URL. It should look like https://yourcompany.atlassian.net (no trailing slash, no path).";
      } else {
        error = `Jira returned an error: ${rawMessage}`;
      }

      return NextResponse.json({ ok: false, error, hint });
    }
  } catch (err) {
    const msg = String(err);
    const isNetworkError = msg.includes("ENOTFOUND") || msg.includes("ECONNREFUSED") || msg.includes("fetch");
    return NextResponse.json({
      ok: false,
      error: isNetworkError ? "Could not reach Jira — the base URL may be unreachable." : `Unexpected error: ${msg}`,
      hint: isNetworkError ? "Check that the Jira base URL is correct and accessible." : undefined,
    });
  }
}
